### ISSUE TITLE
Agartha Discussion

### ISSUE THREAD

**Issue by BelfordZ** [etclabscore/ECIPs#38] opened 2019-10-23 21:03 UTC

**Comment by BelfordZ** [comment] 2019-10-23 21:04
Im not sure its been mentioned, but this would make anyone looking to develop a new EVM would need to implement all previous versions as well.

That being said, we must be prudent to ensure that changes are very well documented, and the implementation of each version can be replicated by following this documentation with relative ease.

We should hold off on including this ECIP until the following are very well defined:

What will be the canonical model for describing the EVM
In what format will changes to this model be proposed
where will the model which specifies each version be located?
Further, it would not be wise to make changes to the EVM until this is sorted out. So to be clear, I don't think we should put a date on this HF until the above is sorted out.

**Comment by soc1c** [comment] 2019-10-24 08:06
Duplicate of https://github.com/ethereumclassic/ECIPs/issues/131

Ref https://github.com/ethereumclassic/ECIPs/commit/3cc13d1a8b9a825df1e278e06fdc44434c7626b6

**Closed as completed by soc1c** 2019-10-24 08:06 UTC
Labels: in progress
